name: Update Repo Name

on:
  watch:
    types: [ started ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: node index.js
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        REPO_ID: ${{ secrets.REPO_ID }}
